improve

diff --git a/home/files/all/bin/waitforboot b/home/files/all/bin/waitforboot
--- a/home/files/all/bin/waitforboot
+++ b/home/files/all/bin/waitforboot
@@ -1,27 +1,90 @@
 #!/bin/bash
 # $Id: 2025-04-16 ststefa $
-# Wait for a system to reboot and be reachable over ssh again
+# Wait for a Linux system to reboot and be reachable over ssh again
 
-TARGET=${1}
-
-ssh_connect() {
-    ssh -o UserKnownHostsFile=/dev/null -o ConnectTimeout=2 ${1} date >> /dev/null 2>&1
-}
-
-if ! ssh_connect "${TARGET}" ; then
-    echo "${TARGET} not reachable"
+if (($# != 1)); then
+    echo "Usage: $(basename ${0}) <host>, where <host> is anything accepted by the ssh command (e.g. "user@host:1234")" >&2
     exit 1
 fi
 
-echo "Waiting for ${TARGET} to be gone"
+# Target host name or ip
+TARGET="${1}"
+# ssh should fail fast if host is in an in-between state
+SSH="ssh -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -o ForwardAgent=no -o ForwardX11=no"
 
-while ssh_connect "${TARGET}" ; do
-    sleep 5;
+ssh_connect() {
+    ${SSH} "${TARGET}" true >/dev/null 2>&1
+}
+
+is_ip() {
+    [[ ${1} =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
+    return $?
+}
+
+RC=0
+
+if ! is_ip "${TARGET}"; then
+    echo "Waiting for ${TARGET}.heldenzeit.net to be dns-resolvable (max 60s)"
+    SECONDS=0
+    RETRIES=0
+    while true; do
+        ((RETRIES++))
+        if ! host "${TARGET}" > /dev/null 2>&1; then
+            echo "dns-resolvable after ${SECONDS}s"
+            break
+        fi
+        if ((SECONDS > 60)); then
+            echo "not dns-resolvable after ${SECONDS}s, bailing out"
+            break
+        fi
+        sleep 5
+    done
+fi
+
+if ssh_connect "${TARGET}"; then
+    SECONDS=0
+    RETRIES=0
+    echo "Waiting for ${TARGET} to be ssh-unreachable (max 300s)"
+    while true; do
+        ((RETRIES++))
+        if ! ssh_connect "${TARGET}"; then
+            echo "ssh-unreachable after ${SECONDS}s"
+            break
+        fi
+        if ((SECONDS > 300)); then
+            echo "not ssh-unreachable after ${SECONDS}s, bailing out"
+            break
+        fi
+        sleep 5
+    done
+fi
+
+SECONDS=0
+RETRIES=0
+echo "Waiting for ${TARGET} to be ssh-reachable (max 60s)"
+while true; do
+    ((RETRIES++))
+    if ssh_connect "${TARGET}"; then
+        echo -n "ssh-reachable after ${SECONDS}s"
+        UPTIME="$(${SSH} ${TARGET} cat /proc/uptime | cut -d . -f1)"
+        if [[ "$UPTIME" =~ ^[0-9]+$ ]]; then
+            echo -n ", remote uptime ${UPTIME}s"
+            if ((UPTIME > 60)); then
+                echo -n ", probably no reboot happened"
+                RC=1
+            fi
+        else
+            echo -n ", remote uptime unknown"
+        fi
+        echo
+        break
+    fi
+    if ((SECONDS > 60)); then
+        echo "not ssh-reachable after ${SECONDS}s, bailing out"
+        RC=1
+        break
+    fi
+    sleep 5
 done
 
-echo "${TARGET} unreachable, system booting"
-
-while ! ssh_connect "${TARGET}" ; do
-    sleep 0
-done
-echo "${TARGET} reachable"
+exit "${RC}"
